version: '3.3'
services: 
    postgres:
        image: postgres
        environment: 
            - DATABASE_HOST=127.0.0.1
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=postgres  

        ports: 
            - "8081:5432"
